package navegantesMaritimos.interfaz;

import javax.swing.*;
import navegantesMaritimos.NavegantesMaritimos;
import navegantesMaritimos.interfaz.validadores.Validador;
import navegantesMaritimos.interfaz.otros.*;

/**
 * Este menu sirve para dar de alta un barco.
 */
public class MenuAltaBarco extends javax.swing.JFrame {

    private final NavegantesMaritimos nav;
    private final JFrame framePadre;
    private final MenuPuerto menuPadre;
    private String nombrePuerto;

    public MenuAltaBarco(NavegantesMaritimos nav, JFrame framePadre, MenuPuerto menuPadre, String nombrePuerto) {
        this.nav = nav;
        this.framePadre = framePadre;
        this.menuPadre = menuPadre;
        this.nombrePuerto = nombrePuerto;
        initComponents();
        inicializarPaises();
        this.setLocationRelativeTo(null);
    }

    private void inicializarPaises() {
        Paises.agregarAComboBox(comboBoxPais);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAltaBarco = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        labelPais = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        comboBoxTipo = new javax.swing.JComboBox();
        labelBandera = new javax.swing.JLabel();
        comboBoxPais = new javax.swing.JComboBox();
        buttonCrear = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de barco");
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelAltaBarco.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)), "Alta de barco"));

        labelNombre.setText("Nombre:");

        labelTipo.setText("Tipo:");

        labelPais.setText("País:");

        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Pesquero", "Pasajeros", "Carga"}));

        labelBandera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navegantesMaritimos/recursos/banderas/null.png"))); // NOI18N
        labelBandera.setToolTipText("");

        comboBoxPais.setModel(new javax.swing.DefaultComboBoxModel());
        comboBoxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPaisActionPerformed(evt);
            }
        });

        buttonCrear.setText("Crear");
        buttonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAltaBarcoLayout = new javax.swing.GroupLayout(panelAltaBarco);
        panelAltaBarco.setLayout(panelAltaBarcoLayout);
        panelAltaBarcoLayout.setHorizontalGroup(
            panelAltaBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAltaBarcoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAltaBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPais)
                    .addGroup(panelAltaBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAltaBarcoLayout.createSequentialGroup()
                            .addComponent(labelNombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelAltaBarcoLayout.createSequentialGroup()
                            .addComponent(labelTipo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelAltaBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelAltaBarcoLayout.createSequentialGroup()
                                    .addComponent(buttonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelAltaBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelAltaBarcoLayout.createSequentialGroup()
                                        .addComponent(comboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelBandera, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAltaBarcoLayout.setVerticalGroup(
            panelAltaBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAltaBarcoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAltaBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAltaBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipo)
                    .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAltaBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAltaBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelPais)
                        .addComponent(comboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelBandera, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelAltaBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCrear)
                    .addComponent(buttonCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAltaBarco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAltaBarco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPaisActionPerformed
        Pais p = (Pais) comboBoxPais.getSelectedItem();
        try {
            labelBandera.setIcon(new ImageIcon(getClass().getResource("../recursos/banderas/" + p.getAlias() + ".png")));
        } catch (Exception e) {
            labelBandera.setIcon(new ImageIcon(getClass().getResource("../recursos/banderas/null.png")));
        }
    }//GEN-LAST:event_comboBoxPaisActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        framePadre.setEnabled(true);
        framePadre.setVisible(true);
        framePadre.toFront();
        menuPadre.actualizarPanelBarcosEspera();
    }//GEN-LAST:event_formWindowClosed

    private void buttonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearActionPerformed
        if (Validador.cantCarac(textFieldNombre, 5, 50)) {
            String nombre = textFieldNombre.getText();
            String tipo = comboBoxTipo.getSelectedItem().toString();
            String pais = comboBoxPais.getSelectedItem().toString();
            boolean correcto = nav.altaBarco(nombre, tipo, pais);
            if (correcto) {
                nav.ponerBarco(nombre, nombrePuerto);
                JOptionPane.showMessageDialog(this, "El barco " + nombre + " se ha dado de alta correctamente.", "Alta de barco exitosa", 1);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No se ha podido crear el barco. Es posible que ya exista un barco con el nombre ingresado. Intentelo nuevamente.", "Error", 0);
            }
        }
    }//GEN-LAST:event_buttonCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAltaBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAltaBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAltaBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAltaBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAltaBarco(null, null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonCrear;
    private javax.swing.JComboBox comboBoxPais;
    private javax.swing.JComboBox comboBoxTipo;
    private javax.swing.JLabel labelBandera;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPais;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JPanel panelAltaBarco;
    private javax.swing.JTextField textFieldNombre;
    // End of variables declaration//GEN-END:variables
}
