package navegantesMaritimos.interfaz;

import javax.swing.*;
import navegantesMaritimos.NavegantesMaritimos;

/**
 * Este menu permite acceder a otras opciones como camino mas corto, verificar
 * distancias entre otras.
 */
public class MenuOtrasOpciones extends javax.swing.JFrame {

    private final NavegantesMaritimos nav;
    private final JFrame framePadre;
    private final MenuPrincipal menuPadre;

    public MenuOtrasOpciones(NavegantesMaritimos nav, JFrame framePadre, MenuPrincipal menuPadre) {
        this.nav = nav;
        this.framePadre = framePadre;
        this.menuPadre = menuPadre;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOtrasOpciones = new javax.swing.JPanel();
        buttonListarPuertosRango = new javax.swing.JButton();
        buttonVerificarRutasDistancia = new javax.swing.JButton();
        buttonCaminoMasCorto = new javax.swing.JButton();
        buttonCaminoNoPasaPor = new javax.swing.JButton();
        buttonDistanciaMasCorta = new javax.swing.JButton();
        buttonListarPuertosBarcosEspera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Otras opciones");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelOtrasOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)), "Otras opciones"));

        buttonListarPuertosRango.setText("Listar puertos en un rango");
        buttonListarPuertosRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListarPuertosRangoActionPerformed(evt);
            }
        });

        buttonVerificarRutasDistancia.setText("Verificar camino entre puertos con distancia menor a...");
        buttonVerificarRutasDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerificarRutasDistanciaActionPerformed(evt);
            }
        });

        buttonCaminoMasCorto.setText("Camino mas corto entre dos puertos");
        buttonCaminoMasCorto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCaminoMasCortoActionPerformed(evt);
            }
        });

        buttonCaminoNoPasaPor.setText("Camino entre dos puertos que no pasa por otro puerto");
        buttonCaminoNoPasaPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCaminoNoPasaPorActionPerformed(evt);
            }
        });

        buttonDistanciaMasCorta.setText("Distancia minima para llegar desde un puerto a otro");
        buttonDistanciaMasCorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDistanciaMasCortaActionPerformed(evt);
            }
        });

        buttonListarPuertosBarcosEspera.setText("Listar todos los puertos que tienen barcos en la cola de espera");
        buttonListarPuertosBarcosEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListarPuertosBarcosEsperaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOtrasOpcionesLayout = new javax.swing.GroupLayout(panelOtrasOpciones);
        panelOtrasOpciones.setLayout(panelOtrasOpcionesLayout);
        panelOtrasOpcionesLayout.setHorizontalGroup(
            panelOtrasOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOtrasOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOtrasOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonListarPuertosBarcosEspera)
                    .addComponent(buttonDistanciaMasCorta)
                    .addComponent(buttonCaminoNoPasaPor)
                    .addComponent(buttonCaminoMasCorto)
                    .addComponent(buttonVerificarRutasDistancia)
                    .addComponent(buttonListarPuertosRango))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOtrasOpcionesLayout.setVerticalGroup(
            panelOtrasOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOtrasOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonListarPuertosRango)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonVerificarRutasDistancia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCaminoMasCorto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCaminoNoPasaPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDistanciaMasCorta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonListarPuertosBarcosEspera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOtrasOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOtrasOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        framePadre.setEnabled(true);
        framePadre.setVisible(true);
        framePadre.toFront();
        menuPadre.actualizarPanelPuertos();
        menuPadre.actualizarPanelRutasMaritimas();
    }//GEN-LAST:event_formWindowClosed

    private void buttonListarPuertosRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListarPuertosRangoActionPerformed
        this.setEnabled(false);
        this.setVisible(false);
        MenuListarPuertosRango menuAux = new MenuListarPuertosRango(nav, this);
        menuAux.setVisible(true);
    }//GEN-LAST:event_buttonListarPuertosRangoActionPerformed

    private void buttonVerificarRutasDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerificarRutasDistanciaActionPerformed
        this.setEnabled(false);
        this.setVisible(false);
        MenuVerificarRutasDistancia menuAux = new MenuVerificarRutasDistancia(nav, this);
        menuAux.setVisible(true);
    }//GEN-LAST:event_buttonVerificarRutasDistanciaActionPerformed

    private void buttonCaminoMasCortoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCaminoMasCortoActionPerformed
        this.setEnabled(false);
        this.setVisible(false);
        MenuCaminoMasCorto menuAux = new MenuCaminoMasCorto(nav, this);
        menuAux.setVisible(true);
    }//GEN-LAST:event_buttonCaminoMasCortoActionPerformed

    private void buttonCaminoNoPasaPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCaminoNoPasaPorActionPerformed
        this.setEnabled(false);
        this.setVisible(false);
        MenuCaminoNoPasaPor menuAux = new MenuCaminoNoPasaPor(nav, this);
        menuAux.setVisible(true);
    }//GEN-LAST:event_buttonCaminoNoPasaPorActionPerformed

    private void buttonDistanciaMasCortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDistanciaMasCortaActionPerformed
        this.setEnabled(false);
        this.setVisible(false);
        MenuDistanciaMasCorta menuAux = new MenuDistanciaMasCorta(nav, this);
        menuAux.setVisible(true);
    }//GEN-LAST:event_buttonDistanciaMasCortaActionPerformed

    private void buttonListarPuertosBarcosEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListarPuertosBarcosEsperaActionPerformed
        this.setEnabled(false);
        this.setVisible(false);
        MenuListarPuertosBarcosEspera menuAux = new MenuListarPuertosBarcosEspera(nav, this);
        menuAux.setVisible(true);
    }//GEN-LAST:event_buttonListarPuertosBarcosEsperaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOtrasOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOtrasOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOtrasOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOtrasOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOtrasOpciones(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCaminoMasCorto;
    private javax.swing.JButton buttonCaminoNoPasaPor;
    private javax.swing.JButton buttonDistanciaMasCorta;
    private javax.swing.JButton buttonListarPuertosBarcosEspera;
    private javax.swing.JButton buttonListarPuertosRango;
    private javax.swing.JButton buttonVerificarRutasDistancia;
    private javax.swing.JPanel panelOtrasOpciones;
    // End of variables declaration//GEN-END:variables
}
