package navegantesMaritimos.interfaz;

import javax.swing.*;
import navegantesMaritimos.NavegantesMaritimos;
import navegantesMaritimos.interfaz.validadores.Validador;
import navegantesMaritimos.interfaz.otros.*;

/**
 * Este menu permite dar de alta una ruta maritima.
 */
public class MenuAltaRutaMaritima extends javax.swing.JFrame {

    private final NavegantesMaritimos nav;
    private final JFrame framePadre;
    private final MenuPrincipal menuPadre;

    public MenuAltaRutaMaritima(NavegantesMaritimos nav, JFrame framePadre, MenuPrincipal menuPadre) {
        this.nav = nav;
        this.framePadre = framePadre;
        this.menuPadre = menuPadre;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAltaRutaMaritima = new javax.swing.JPanel();
        buttonCrear = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        labelPuertoOrigen = new javax.swing.JLabel();
        labelPuertoDestino = new javax.swing.JLabel();
        labelSelecPuertoDestino = new javax.swing.JLabel();
        labelSelecPuertoOrigen = new javax.swing.JLabel();
        labelDistancia = new javax.swing.JLabel();
        textFieldDistancia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelAltaRutaMaritima.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)), "Alta de ruta maritima"));

        buttonCrear.setText("Crear");
        buttonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        labelPuertoOrigen.setText("1er Puerto");

        labelPuertoDestino.setText("2do Puerto");

        labelSelecPuertoDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelSelecPuertoDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSelecPuertoDestinoMouseClicked(evt);
            }
        });

        labelSelecPuertoOrigen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelSelecPuertoOrigen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSelecPuertoOrigenMouseClicked(evt);
            }
        });

        labelDistancia.setText("Distancia:");

        javax.swing.GroupLayout panelAltaRutaMaritimaLayout = new javax.swing.GroupLayout(panelAltaRutaMaritima);
        panelAltaRutaMaritima.setLayout(panelAltaRutaMaritimaLayout);
        panelAltaRutaMaritimaLayout.setHorizontalGroup(
            panelAltaRutaMaritimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAltaRutaMaritimaLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(buttonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelAltaRutaMaritimaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelAltaRutaMaritimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAltaRutaMaritimaLayout.createSequentialGroup()
                        .addComponent(labelDistancia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAltaRutaMaritimaLayout.createSequentialGroup()
                        .addGroup(panelAltaRutaMaritimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPuertoOrigen)
                            .addComponent(labelSelecPuertoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAltaRutaMaritimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSelecPuertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPuertoDestino))))
                .addGap(50, 50, 50))
        );
        panelAltaRutaMaritimaLayout.setVerticalGroup(
            panelAltaRutaMaritimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAltaRutaMaritimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAltaRutaMaritimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPuertoDestino)
                    .addComponent(labelPuertoOrigen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAltaRutaMaritimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSelecPuertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSelecPuertoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panelAltaRutaMaritimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDistancia)
                    .addComponent(textFieldDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAltaRutaMaritimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCrear)
                    .addComponent(buttonCancelar))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAltaRutaMaritima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAltaRutaMaritima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearActionPerformed
        if (Validador.noVacio(labelSelecPuertoOrigen)
                && Validador.noVacio(labelSelecPuertoDestino)
                && Validador.enteroRango(textFieldDistancia, 1, 10000)) {
            String puertoOrigen = labelSelecPuertoOrigen.getText();
            String puertoDestino = labelSelecPuertoDestino.getText();            
            int distancia = Integer.parseInt(textFieldDistancia.getText());
            boolean correcto = nav.altaRutaMaritima(puertoOrigen, puertoDestino, distancia);
            if (correcto) {
                JOptionPane.showMessageDialog(this, "La ruta maritima entre el puerto "+puertoOrigen+" y el puerto "+puertoDestino+" se ha dado de alta correctamente.", "Alta de ruta maritima exitosa", 1);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No se ha podido crear la ruta maritima. Es posible que ya exista una ruta maritima entre los puertos indicados. Intentelo nuevamente.", "Error", 0);
            }
        }
    }//GEN-LAST:event_buttonCrearActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void labelSelecPuertoOrigenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSelecPuertoOrigenMouseClicked
        this.setEnabled(false);
        this.setVisible(false);
        MenuSelectorPuerto menuAux = new MenuSelectorPuerto(nav, this, labelSelecPuertoOrigen);
        menuAux.setVisible(true);
    }//GEN-LAST:event_labelSelecPuertoOrigenMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        framePadre.setEnabled(true);
        framePadre.setVisible(true);
        framePadre.toFront();
        menuPadre.actualizarPanelRutasMaritimas();
    }//GEN-LAST:event_formWindowClosed

    private void labelSelecPuertoDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSelecPuertoDestinoMouseClicked
        this.setEnabled(false);
        this.setVisible(false);
        MenuSelectorPuerto menuAux = new MenuSelectorPuerto(nav, this, labelSelecPuertoDestino);
        menuAux.setVisible(true);
    }//GEN-LAST:event_labelSelecPuertoDestinoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAltaRutaMaritima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAltaRutaMaritima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAltaRutaMaritima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAltaRutaMaritima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAltaRutaMaritima(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonCrear;
    private javax.swing.JLabel labelDistancia;
    private javax.swing.JLabel labelPuertoDestino;
    private javax.swing.JLabel labelPuertoOrigen;
    private javax.swing.JLabel labelSelecPuertoDestino;
    private javax.swing.JLabel labelSelecPuertoOrigen;
    private javax.swing.JPanel panelAltaRutaMaritima;
    private javax.swing.JTextField textFieldDistancia;
    // End of variables declaration//GEN-END:variables
}
