package navegantesMaritimos.interfaz;

import javax.swing.*;
import navegantesMaritimos.NavegantesMaritimos;
import navegantesMaritimos.interfaz.validadores.Validador;

/**
 * Este menu permite enviar un barco desde las darsenas de un puerto origen a la
 * cola de espera de un puerto destino.
 */
public class MenuEnviarBarco extends javax.swing.JFrame {

    private final NavegantesMaritimos nav;
    private final JFrame framePadre;
    private final MenuPuerto menuPadre;
    private final String puertoOrigen;
    private final String barco;

    public MenuEnviarBarco(NavegantesMaritimos nav, JFrame framePadre, MenuPuerto menuPadre, String puertoOrigen, String barco) {
        this.nav = nav;
        this.framePadre = framePadre;
        this.menuPadre = menuPadre;
        this.puertoOrigen = puertoOrigen;
        this.barco = barco;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEnviarBarco = new javax.swing.JPanel();
        buttonEnviar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        labelPuertoDestino = new javax.swing.JLabel();
        labelSelecPuertoDestino = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enviar barco");
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelEnviarBarco.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)), "Enviar barco"));

        buttonEnviar.setText("Enviar");
        buttonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnviarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        labelPuertoDestino.setText("Puerto destino");

        labelSelecPuertoDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelSelecPuertoDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSelecPuertoDestinoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelEnviarBarcoLayout = new javax.swing.GroupLayout(panelEnviarBarco);
        panelEnviarBarco.setLayout(panelEnviarBarcoLayout);
        panelEnviarBarcoLayout.setHorizontalGroup(
            panelEnviarBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnviarBarcoLayout.createSequentialGroup()
                .addGroup(panelEnviarBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEnviarBarcoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEnviarBarcoLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(panelEnviarBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPuertoDestino)
                            .addComponent(labelSelecPuertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelEnviarBarcoLayout.setVerticalGroup(
            panelEnviarBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEnviarBarcoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPuertoDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSelecPuertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelEnviarBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEnviar)
                    .addComponent(buttonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEnviarBarco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEnviarBarco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnviarActionPerformed
        if (Validador.noVacio(labelSelecPuertoDestino)) {
            String puertoDestino = labelSelecPuertoDestino.getText();
            boolean correcto = nav.enviarBarco(barco, puertoOrigen, puertoDestino);
            if (correcto) {
                JOptionPane.showMessageDialog(this, "El barco " + barco + " ha sido enviado a la cola de espera del puerto " + puertoDestino + " correctamente.", "Envio de barco exitoso", 1);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No se ha podido enviar el barco. Intentelo nuevamente", "Error", 0);
            }
        }
    }//GEN-LAST:event_buttonEnviarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void labelSelecPuertoDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSelecPuertoDestinoMouseClicked
        this.setEnabled(false);
        this.setVisible(false);
        MenuSelectorPuerto menuAux = new MenuSelectorPuerto(nav, this, labelSelecPuertoDestino);
        menuAux.setVisible(true);
    }//GEN-LAST:event_labelSelecPuertoDestinoMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        framePadre.setEnabled(true);
        framePadre.setVisible(true);
        framePadre.toFront();
        menuPadre.actualizarPanelDarsenas();
        menuPadre.actualizarPanelBarcosEspera();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEnviarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEnviarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEnviarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEnviarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEnviarBarco(null, null, null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonEnviar;
    private javax.swing.JLabel labelPuertoDestino;
    private javax.swing.JLabel labelSelecPuertoDestino;
    private javax.swing.JPanel panelEnviarBarco;
    // End of variables declaration//GEN-END:variables
}
