package navegantesMaritimos.interfaz;

import javax.swing.*;
import navegantesMaritimos.NavegantesMaritimos;
import navegantesMaritimos.interfaz.validadores.Validador;
import navegantesMaritimos.interfaz.otros.*;

/**
 * Este menu sirbe para dar de alta un puerto.
 */
public class MenuAltaPuerto extends JFrame {

    private final NavegantesMaritimos nav;
    private final JFrame framePadre;
    private final MenuPrincipal menuPadre;

    public MenuAltaPuerto(NavegantesMaritimos nav, JFrame framePadre, MenuPrincipal menuPadre) {
        this.nav = nav;
        this.framePadre = framePadre;
        this.menuPadre = menuPadre;
        initComponents();
        inicializarPaises();
        this.setLocationRelativeTo(null);
    }

    private void inicializarPaises() {
        Paises.agregarAComboBox(comboBoxPais);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAltaPuerto = new javax.swing.JPanel();
        buttonCrear = new javax.swing.JButton();
        labelNombre = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        labelPais = new javax.swing.JLabel();
        comboBoxPais = new javax.swing.JComboBox();
        buttonCancelar = new javax.swing.JButton();
        labelBandera = new javax.swing.JLabel();
        labelCantDarsenas = new javax.swing.JLabel();
        textFieldCantDarsenas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de puerto");
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelAltaPuerto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)), "Alta de puerto"));

        buttonCrear.setText("Crear");
        buttonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearActionPerformed(evt);
            }
        });

        labelNombre.setText("Nombre:");

        textFieldNombre.setToolTipText("El valor ingresado debe estar compuesto unicamente por letras y numeros, no debe de tener mas de 50 caracteres.");

        labelPais.setText("País:");

        comboBoxPais.setModel(new javax.swing.DefaultComboBoxModel());
        comboBoxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPaisActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        labelBandera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navegantesMaritimos/recursos/banderas/null.png"))); // NOI18N
        labelBandera.setToolTipText("");

        labelCantDarsenas.setText("Cantidad de darsenas:");

        javax.swing.GroupLayout panelAltaPuertoLayout = new javax.swing.GroupLayout(panelAltaPuerto);
        panelAltaPuerto.setLayout(panelAltaPuertoLayout);
        panelAltaPuertoLayout.setHorizontalGroup(
            panelAltaPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAltaPuertoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAltaPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAltaPuertoLayout.createSequentialGroup()
                        .addComponent(labelCantDarsenas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldCantDarsenas, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAltaPuertoLayout.createSequentialGroup()
                        .addGroup(panelAltaPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addComponent(labelPais))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAltaPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAltaPuertoLayout.createSequentialGroup()
                                .addComponent(comboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(labelBandera, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textFieldNombre))))
                .addContainerGap())
            .addGroup(panelAltaPuertoLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(buttonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAltaPuertoLayout.setVerticalGroup(
            panelAltaPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAltaPuertoLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panelAltaPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAltaPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBandera, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAltaPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelPais)
                        .addComponent(comboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAltaPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCantDarsenas)
                    .addComponent(textFieldCantDarsenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAltaPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCrear)
                    .addComponent(buttonCancelar))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAltaPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAltaPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void comboBoxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPaisActionPerformed
        Pais p = (Pais) comboBoxPais.getSelectedItem();
        try {
            labelBandera.setIcon(new ImageIcon(getClass().getResource("../recursos/banderas/" + p.getAlias() + ".png")));
        } catch (Exception e) {
            labelBandera.setIcon(new ImageIcon(getClass().getResource("../recursos/banderas/null.png")));
        }

    }//GEN-LAST:event_comboBoxPaisActionPerformed

    private void buttonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearActionPerformed
        if (Validador.cantCarac(textFieldNombre, 5, 50)
                && Validador.enteroRango(textFieldCantDarsenas, 1, 1000)) {
            String nombre = textFieldNombre.getText();
            String pais = comboBoxPais.getSelectedItem().toString();
            int cantDarsenas = Integer.parseInt(textFieldCantDarsenas.getText());
            boolean correcto = nav.altaPuerto(nombre, pais, cantDarsenas);
            if (correcto) {
                JOptionPane.showMessageDialog(this, "El puerto " + nombre + " se ha dado de alta correctamente.", "Alta de puerto exitosa", 1);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No se ha podido crear el puerto. Es posible que ya exista un puerto con el nombre ingresado. Intentelo nuevamente.", "Error", 0);
            }
        }
    }//GEN-LAST:event_buttonCrearActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        framePadre.setEnabled(true);
        framePadre.setVisible(true);
        framePadre.toFront();
        menuPadre.actualizarPanelPuertos();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAltaPuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAltaPuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAltaPuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAltaPuerto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAltaPuerto(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonCrear;
    private javax.swing.JComboBox comboBoxPais;
    private javax.swing.JLabel labelBandera;
    private javax.swing.JLabel labelCantDarsenas;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPais;
    private javax.swing.JPanel panelAltaPuerto;
    private javax.swing.JTextField textFieldCantDarsenas;
    private javax.swing.JTextField textFieldNombre;
    // End of variables declaration//GEN-END:variables
}
