package navegantesMaritimos.interfaz;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;
import lineales.lista.Lista;
import navegantesMaritimos.NavegantesMaritimos;
import navegantesMaritimos.interfaz.otros.*;

/**
 * Este menu permite realizar la opcion de listar todos los puertos que tienen
 * que tienen barcos en la cola de espera.
 */
public class MenuListarPuertosBarcosEspera extends javax.swing.JFrame {

    private final NavegantesMaritimos nav;
    private final JFrame framePadre;

    public MenuListarPuertosBarcosEspera(NavegantesMaritimos nav, JFrame framePadre) {
        this.nav = nav;
        this.framePadre = framePadre;
        initComponents();
        actualizarPanelPuertos();
        this.setLocationRelativeTo(null);
    }

    public void actualizarPanelPuertos() {
        panelPuertos.setPreferredSize(new Dimension(384, 64));
        panelPuertos.removeAll();
        Lista<String> puertos = nav.listarPuertosBarcosEspera();
        if (puertos != null) {
            int fila = 0;
            int col = 0;
            for (int i = 1; i <= puertos.longitud(); i++) {
                String[] puerto = nav.arregloDatosPuerto(puertos.recuperar(i));
                agregarPuertoAPanel(puerto, col, fila);
                if (i % 6 == 0) {
                    fila++;
                    col -= 6;
                    double preferedWidth = panelPuertos.getPreferredSize().getWidth();
                    double preferedHeight = panelPuertos.getPreferredSize().getHeight();
                    panelPuertos.setPreferredSize(new Dimension((int) preferedWidth, (int) preferedHeight + 64));
                }
                col++;
            }
        }
        panelPuertos.repaint();
    }

    public void agregarPuertoAPanel(String[] puerto, int col, int fila) {
        final JLabel labelPuerto = new JLabel();
        labelPuerto.setBounds(64 * col, 64 * fila, 64, 64);
        labelPuerto.setText(puerto[0]);
        labelPuerto.setToolTipText(
                "<html>"
                + "<p>" + puerto[0] + "</p>"
                + "<p>" + puerto[1] + "</p>"
                + "<p>" + puerto[2] + " darsenas</p>"
                + "</html>");
        labelPuerto.setIcon(new ImageIcon(getClass().getResource("../recursos/puertos/puerto.png")));
        JLabel labelPais = new JLabel();
        labelPais.setBounds((64 * col) + 34, (64 * fila) + 44, 30, 20);
        labelPais.setIcon(new ImageIcon(getClass().getResource("../recursos/banderas/" + Paises.conseguirAlias(puerto[1]) + ".png")));
        labelPuerto.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                Border border = LineBorder.createGrayLineBorder();
                labelPuerto.setBorder(border);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                labelPuerto.setBorder(null);
            }
        });
        panelPuertos.add(labelPais);
        panelPuertos.add(labelPuerto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCaminoMasCorto = new javax.swing.JPanel();
        scrollPuertos = new javax.swing.JScrollPane();
        panelPuertos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Camino mas corto entre dos puertos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelCaminoMasCorto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)), "Listar todos los puertos que tienen barcos en la cola de espera"));

        scrollPuertos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPuertos.setAutoscrolls(true);
        scrollPuertos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrollPuertos.setHorizontalScrollBar(null);

        panelPuertos.setBackground(new java.awt.Color(102, 102, 102));
        panelPuertos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelPuertos.setPreferredSize(new java.awt.Dimension(384, 64));

        javax.swing.GroupLayout panelPuertosLayout = new javax.swing.GroupLayout(panelPuertos);
        panelPuertos.setLayout(panelPuertosLayout);
        panelPuertosLayout.setHorizontalGroup(
            panelPuertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        panelPuertosLayout.setVerticalGroup(
            panelPuertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        scrollPuertos.setViewportView(panelPuertos);

        javax.swing.GroupLayout panelCaminoMasCortoLayout = new javax.swing.GroupLayout(panelCaminoMasCorto);
        panelCaminoMasCorto.setLayout(panelCaminoMasCortoLayout);
        panelCaminoMasCortoLayout.setHorizontalGroup(
            panelCaminoMasCortoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCaminoMasCortoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPuertos, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCaminoMasCortoLayout.setVerticalGroup(
            panelCaminoMasCortoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCaminoMasCortoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPuertos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCaminoMasCorto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCaminoMasCorto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        framePadre.setEnabled(true);
        framePadre.setVisible(true);
        framePadre.toFront();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuListarPuertosBarcosEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuListarPuertosBarcosEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuListarPuertosBarcosEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuListarPuertosBarcosEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuListarPuertosBarcosEspera(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelCaminoMasCorto;
    private javax.swing.JPanel panelPuertos;
    private javax.swing.JScrollPane scrollPuertos;
    // End of variables declaration//GEN-END:variables
}
